
class Config {

  /// Generated by Flangapp PRO 03-12-2024 19:41
  /// App UID: 583c402e-25a8-ed66-1ff6-8a57d446f64b
  /// Version: 1.0.0
  /// API server: https://flangapi.impeltech.ru:8443/

  /// *** Main settings *** ///
  static String apiUrl = "https://flangapi.impeltech.ru:8443/";
  static String appUid = "583c402e-25a8-ed66-1ff6-8a57d446f64b";
  static String oneSignalPushId = "210df28b-0bdb-47ed-a9aa-deaca234a7e7";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#F44336";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}